// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxppialptyjpczegaamo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4cHBpYWxwdHlqcGN6ZWdhYW1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3OTQwNzIsImV4cCI6MjA3MjM3MDA3Mn0.IlVNfNkwsE9B2lynJNtzGTYre1hR91aNZgKLa6QGi8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});